apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-demo
  labels:
    app: dotnet-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-demo
  template:
    metadata:
      labels:
        app: dotnet-demo
    spec:
      containers:
        - name: dotnet-demo
          image: siddhanta28/dotnet-app:latest
          ports:
            - containerPort: 80

