version: '3'
services:
   db:
     image: mysql:5.7
     volumes:
       - data:/var/lib/mysql
     networks:
       - network
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: dotnet
       MYSQL_DATABASE: dbuser
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dotnet
   dotnet:
     depends_on:
       - db
     build:
       context: .
       dockerfile: Dockerfile
     image: dotnet-image:latest
     ports:
       - "5051:80"
     restart: always
     environment:
       DOTNET_DB_HOST: db:3306
       DOTNET_DB_USER: dbuser
       DOTNET_DB_PASSWORD: dotnet
       DOTNET_DB_NAME: dbuser
     networks:
       - network

volumes:
    data:

networks:
    network:
